### ISSUE TITLE
AttributeError: module 'types' has no attribute 'ListType'

### ISSUE THREAD

**Issue by vreen** [knockrentals/scrapy-elasticsearch#39]
After adding ElasticSearchPipeline to my ITEM_PIPELINES array I see this error: 

Traceback (most recent call last):
  File "/home/spl/Code/python_env/myenv/lib/python3.5/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/spl/Code/python_env/myenv/lib/python3.5/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 108, in process_item
    if isinstance(item, types.GeneratorType) or isinstance(item, types.ListType):
AttributeError: module 'types' has no attribute 'ListType'

All involved packages are installed in the most recent versions.

**Comment by jayzeng** [comment]
@vreen what version of Python do you use?

**Comment by jayzeng** [comment]
@vreen I pushed a new build, please give it a test and let me know

**Comment by jayzeng** [comment]
https://github.com/knockrentals/scrapy-elasticsearch/commit/0aec4cc38f55eec02cdf18c3e360bcf23764daeb

**Comment by vreen** [comment]
@jayzeng I am using Python 3.5.2
Your commit fixes the 'ListType' issue but heads to the next one: 

Traceback (most recent call last):
  File "/home/spl/Code/python_env/myenv/lib/python3.5/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/home/spl/Code/python_env/myenv/lib/python3.5/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 112, in process_item
    self.index_item(item)
  File "/home/spl/Code/python_env/myenv/lib/python3.5/site-packages/scrapyelasticsearch/scrapyelasticsearch.py", line 94, in index_item
    item_id = hashlib.sha1(unique_key).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

**Comment by jayzeng** [comment]
@vreen never tested it w/ Python 3, I will make whatever changes required to make it compatible. Stay tuned

**Comment by vreen** [comment]
@jayzeng Line 94 has to be modified accordingly:
  item_id = hashlib.sha1(unique_key.**encode('utf-8')**).hexdigest()

After that, this nice Pipeline works with Python 3.5!
Thanks for having an eye on this.

**Comment by jayzeng** [comment]
@vreen sorry I linked the wrong commit for the fix, here it is https://github.com/knockrentals/scrapy-elasticsearch/commit/8aa92f6c5a57c919fa3cd591e7f297323b2de627, it is essentially the same as what you did, except it is added in the get_unique_key(), which is more appricate. Either way, I pushed my change to pypi, feel free to pull the latest. 

Have fun :)
